### ISSUE TITLE
On installation - NameError: name 'read_md' is not defined

### ISSUE THREAD

**Issue by philmade** [hmleal/django-podcast#9]
The above error happens when running pip install django-podcast.

I tried to install manually after this name error, but after manual installtion django keeps saying ModuleNotFoundError: No module named 'podcast' after installing to a virtualenv.

**Comment by hmleal** [comment]
Sorry for the 3 years of delay on that. I'm starting to work again in this project and soon I get it fixed I let you now

**Comment by hmleal** [comment]
Try to install it again or upload the package

```
pip install django_podcast -U
```

**Comment by philmade** [comment]
Hey thanks Henrique - right on cue! I was just talking about getting this
podcast started again!
